### ISSUE TITLE
How to incorporate an additional CRISPR spacer database?

### ISSUE THREAD

**Issue by ErnieHsieh** [edzuf/CrisprOpenDB#17]
Dear author,

I would like to ask if I have an our own spacer database (collected from binned MAG-based CRISPR arrays generated using CRISPRDetect3.0) and would like to additionally use it to predict hosts for my vOTUs using this prediction tool, could you please teach me how I should do to incorporate our DB in the directory and run it?

Can I just directly put my spacer.fasta (or any proper formats) in the './CrisprOpenDB/SpacersDB' then directly run the 'CL_Interface.py'? or should I change/modify anything to correctly use it? or I should manually do it with blastn etc.? I am new to carry out phage-host prediction analysis.

I have initially run it on my vOTUs using your default spacer database and successfully generated some output for my vOTUs, but we also want to run it with an additional DB in parallel to get extra predictions. If you have any ideas/comments please let me know how to make it. 

Many thanks.

Best wishes,
Ernie

**Comment by geboro** [comment]
Hello!
Is there any further response on this? I have a large spacer database from genome collections from our model system with CRISPR spacers that have no representatives in the OpenDB. 

I can add them to the Spacers.fasta file and they get picked in the BLAST table, but since they are not in the sql database they turn out as "No hit found"... 

It would be amazing to add custom spacers to the database!
