### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'blastn'

### ISSUE THREAD

**Issue by linsalrob** [edzuf/CrisprOpenDB#9]
Following the install instructions gives the error `FileNotFoundError: [Errno 2] No such file or directory: 'blastn'`

The conda environment needs either [fasta](https://anaconda.org/biobuilds/fasta) (_Note:_ that is in the `biobuilds` channel) or [NCBI blast](https://anaconda.org/bioconda/blast).

(It appears the default install is blast, so that should be included at least).

**Comment by plpla** [comment]
Thank you for reporting this. We understand some users might not have NCBI blast already installed on their computer so we added instructions to the README on how to add Blast to the conda env if it is needed. We still think users should rely on their own blast installation if they have one since the version available through Bioconda is not the most recent.
